### ISSUE TITLE
Enable travis CI

### ISSUE THREAD

**Issue by simnalamburt** [slate/slate-irc-parser#5]
<img width=350 alt="Screenshot of Travis CI profile page" src="https://cloud.githubusercontent.com/assets/4435445/14770027/81420e4a-0aa1-11e6-8547-87c9fbda477a.png">

@tj, looks like I do not have the admin access to this repo so I couldn't not enable travis CI to this repo. Can you help me out?

**Comment by simnalamburt** [comment]
@tj Help 😢

**Comment by tj** [comment]
yo sorry, made you an admin, should be fine now

**Comment by simnalamburt** [comment]
Thank you very much! I promise that I won't abuse it!
